/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasicErc20 } from "./BasicErc20";
export type { BasicErc20Factory } from "./BasicErc20Factory";
export * as factories from "./factories";
export { BasicErc20__factory } from "./factories/BasicErc20__factory";
export { BasicErc20Factory__factory } from "./factories/BasicErc20Factory__factory";
