/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export declare namespace LensERC1155 {
  export type TokenParamsStruct = {
    metadataURI: string;
    maxSupply: BigNumberish;
    mintRate: BigNumberish;
  };

  export type TokenParamsStructOutput = [
    metadataURI: string,
    maxSupply: bigint,
    mintRate: bigint,
  ] & { metadataURI: string; maxSupply: bigint; mintRate: bigint };
}

export declare namespace BaseToken {
  export type MinterStruct = { addr: AddressLike; label: string };

  export type MinterStructOutput = [addr: string, label: string] & {
    addr: string;
    label: string;
  };
}

export declare namespace Administered {
  export type AdminStatusChangeParamStruct = {
    addr: AddressLike;
    isAdmin: boolean;
  };

  export type AdminStatusChangeParamStructOutput = [addr: string, isAdmin: boolean] & {
    addr: string;
    isAdmin: boolean;
  };
}

export interface LensERC1155Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MINT_RATE_COOLDOWN'
      | 'addMinters'
      | 'balanceOf'
      | 'balanceOfBatch'
      | 'burn'
      | 'burnBatch'
      | 'canAdmin'
      | 'isApprovedForAll'
      | 'isMinter'
      | 'leaveAsAdmin'
      | 'maxSupply'
      | 'mint'
      | 'mintBatch'
      | 'mintRate'
      | 'mintRateCooldownEnd'
      | 'owner'
      | 'removeMinters'
      | 'renounceOwnership'
      | 'revision'
      | 'safeBatchTransferFrom'
      | 'safeTransferFrom'
      | 'setAdmins'
      | 'setApprovalForAll'
      | 'setMaxSupply'
      | 'setMintRate'
      | 'setURI'
      | 'supportsInterface'
      | 'totalSupply'
      | 'transferOwnership'
      | 'uri',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'AdminStatusChanged'
      | 'ApprovalForAll'
      | 'Lens_Token_AdminStatusChanged'
      | 'Lens_Token_MaxSupplyUpdated'
      | 'Lens_Token_MintRateChanged'
      | 'Lens_Token_MinterAdded'
      | 'Lens_Token_MinterRemoved'
      | 'Lens_Token_OwnershipTransferred'
      | 'Lens_Token_SetMetadataURI'
      | 'OwnershipTransferred'
      | 'TransferBatch'
      | 'TransferSingle'
      | 'URI',
  ): EventFragment;

  encodeFunctionData(functionFragment: 'MINT_RATE_COOLDOWN', values?: undefined): string;
  encodeFunctionData(functionFragment: 'addMinters', values: [BaseToken.MinterStruct[]]): string;
  encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'balanceOfBatch',
    values: [AddressLike[], BigNumberish[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'burn',
    values: [AddressLike, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'burnBatch',
    values: [AddressLike, BigNumberish[], BigNumberish[]],
  ): string;
  encodeFunctionData(functionFragment: 'canAdmin', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'isApprovedForAll',
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'isMinter', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'leaveAsAdmin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'maxSupply', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'mint',
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintBatch',
    values: [AddressLike, BigNumberish[], BigNumberish[], BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'mintRate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mintRateCooldownEnd', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'removeMinters', values: [AddressLike[]]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'revision', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'safeBatchTransferFrom',
    values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'safeTransferFrom',
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAdmins',
    values: [Administered.AdminStatusChangeParamStruct[]],
  ): string;
  encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
  encodeFunctionData(functionFragment: 'setMaxSupply', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'setMintRate', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'setURI', values: [string]): string;
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'MINT_RATE_COOLDOWN', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addMinters', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'burnBatch', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'canAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isMinter', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'leaveAsAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'maxSupply', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mintBatch', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mintRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mintRateCooldownEnd', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'removeMinters', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revision', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setAdmins', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setMaxSupply', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setMintRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setURI', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
}

export namespace AdminStatusChangedEvent {
  export type InputTuple = [admin: AddressLike, newStatus: boolean];
  export type OutputTuple = [admin: string, newStatus: boolean];
  export interface OutputObject {
    admin: string;
    newStatus: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
  export type OutputTuple = [account: string, operator: string, approved: boolean];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_AdminStatusChangedEvent {
  export type InputTuple = [addr: AddressLike, newStatus: boolean];
  export type OutputTuple = [addr: string, newStatus: boolean];
  export interface OutputObject {
    addr: string;
    newStatus: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_MaxSupplyUpdatedEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_MintRateChangedEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_MinterAddedEvent {
  export type InputTuple = [minter: AddressLike, label: string];
  export type OutputTuple = [minter: string, label: string];
  export interface OutputObject {
    minter: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_MinterRemovedEvent {
  export type InputTuple = [minter: AddressLike];
  export type OutputTuple = [minter: string];
  export interface OutputObject {
    minter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Lens_Token_SetMetadataURIEvent {
  export type InputTuple = [metadataURI: string];
  export type OutputTuple = [metadataURI: string];
  export interface OutputObject {
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[],
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[],
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish,
  ];
  export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LensERC1155 extends BaseContract {
  connect(runner?: ContractRunner | null): LensERC1155;
  waitForDeployment(): Promise<this>;

  interface: LensERC1155Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  MINT_RATE_COOLDOWN: TypedContractMethod<[], [bigint], 'view'>;

  addMinters: TypedContractMethod<[minters_: BaseToken.MinterStruct[]], [void], 'nonpayable'>;

  balanceOf: TypedContractMethod<[account: AddressLike, id: BigNumberish], [bigint], 'view'>;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    'view'
  >;

  burn: TypedContractMethod<
    [account: AddressLike, id: BigNumberish, value: BigNumberish],
    [void],
    'nonpayable'
  >;

  burnBatch: TypedContractMethod<
    [account: AddressLike, ids: BigNumberish[], values: BigNumberish[]],
    [void],
    'nonpayable'
  >;

  canAdmin: TypedContractMethod<[user: AddressLike], [boolean], 'view'>;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    'view'
  >;

  isMinter: TypedContractMethod<[addr: AddressLike], [boolean], 'view'>;

  leaveAsAdmin: TypedContractMethod<[], [void], 'nonpayable'>;

  maxSupply: TypedContractMethod<[], [bigint], 'view'>;

  mint: TypedContractMethod<
    [account: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike],
    [void],
    'payable'
  >;

  mintBatch: TypedContractMethod<
    [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike],
    [void],
    'payable'
  >;

  mintRate: TypedContractMethod<[], [bigint], 'view'>;

  mintRateCooldownEnd: TypedContractMethod<[], [bigint], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  removeMinters: TypedContractMethod<[minters_: AddressLike[]], [void], 'nonpayable'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  revision: TypedContractMethod<[], [bigint], 'view'>;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      amounts: BigNumberish[],
      data: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  safeTransferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike],
    [void],
    'nonpayable'
  >;

  setAdmins: TypedContractMethod<
    [_admins: Administered.AdminStatusChangeParamStruct[]],
    [void],
    'nonpayable'
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    'nonpayable'
  >;

  setMaxSupply: TypedContractMethod<[newMaxSupply: BigNumberish], [void], 'nonpayable'>;

  setMintRate: TypedContractMethod<[newMintRate: BigNumberish], [void], 'nonpayable'>;

  setURI: TypedContractMethod<[newuri: string], [void], 'nonpayable'>;

  supportsInterface: TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;

  totalSupply: TypedContractMethod<[], [bigint], 'view'>;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  uri: TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'MINT_RATE_COOLDOWN'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'addMinters',
  ): TypedContractMethod<[minters_: BaseToken.MinterStruct[]], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'balanceOf',
  ): TypedContractMethod<[account: AddressLike, id: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'balanceOfBatch',
  ): TypedContractMethod<[accounts: AddressLike[], ids: BigNumberish[]], [bigint[]], 'view'>;
  getFunction(
    nameOrSignature: 'burn',
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish, value: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'burnBatch',
  ): TypedContractMethod<
    [account: AddressLike, ids: BigNumberish[], values: BigNumberish[]],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'canAdmin',
  ): TypedContractMethod<[user: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isApprovedForAll',
  ): TypedContractMethod<[account: AddressLike, operator: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isMinter',
  ): TypedContractMethod<[addr: AddressLike], [boolean], 'view'>;
  getFunction(nameOrSignature: 'leaveAsAdmin'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'maxSupply'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'mint',
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'mintBatch',
  ): TypedContractMethod<
    [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike],
    [void],
    'payable'
  >;
  getFunction(nameOrSignature: 'mintRate'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'mintRateCooldownEnd'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'removeMinters',
  ): TypedContractMethod<[minters_: AddressLike[]], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'revision'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'safeBatchTransferFrom',
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      amounts: BigNumberish[],
      data: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'safeTransferFrom',
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setAdmins',
  ): TypedContractMethod<
    [_admins: Administered.AdminStatusChangeParamStruct[]],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setApprovalForAll',
  ): TypedContractMethod<[operator: AddressLike, approved: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setMaxSupply',
  ): TypedContractMethod<[newMaxSupply: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setMintRate',
  ): TypedContractMethod<[newMintRate: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setURI',
  ): TypedContractMethod<[newuri: string], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'supportsInterface',
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;
  getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'uri'): TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;

  getEvent(
    key: 'AdminStatusChanged',
  ): TypedContractEvent<
    AdminStatusChangedEvent.InputTuple,
    AdminStatusChangedEvent.OutputTuple,
    AdminStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: 'ApprovalForAll',
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_AdminStatusChanged',
  ): TypedContractEvent<
    Lens_Token_AdminStatusChangedEvent.InputTuple,
    Lens_Token_AdminStatusChangedEvent.OutputTuple,
    Lens_Token_AdminStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_MaxSupplyUpdated',
  ): TypedContractEvent<
    Lens_Token_MaxSupplyUpdatedEvent.InputTuple,
    Lens_Token_MaxSupplyUpdatedEvent.OutputTuple,
    Lens_Token_MaxSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_MintRateChanged',
  ): TypedContractEvent<
    Lens_Token_MintRateChangedEvent.InputTuple,
    Lens_Token_MintRateChangedEvent.OutputTuple,
    Lens_Token_MintRateChangedEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_MinterAdded',
  ): TypedContractEvent<
    Lens_Token_MinterAddedEvent.InputTuple,
    Lens_Token_MinterAddedEvent.OutputTuple,
    Lens_Token_MinterAddedEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_MinterRemoved',
  ): TypedContractEvent<
    Lens_Token_MinterRemovedEvent.InputTuple,
    Lens_Token_MinterRemovedEvent.OutputTuple,
    Lens_Token_MinterRemovedEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_OwnershipTransferred',
  ): TypedContractEvent<
    Lens_Token_OwnershipTransferredEvent.InputTuple,
    Lens_Token_OwnershipTransferredEvent.OutputTuple,
    Lens_Token_OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'Lens_Token_SetMetadataURI',
  ): TypedContractEvent<
    Lens_Token_SetMetadataURIEvent.InputTuple,
    Lens_Token_SetMetadataURIEvent.OutputTuple,
    Lens_Token_SetMetadataURIEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'TransferBatch',
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: 'TransferSingle',
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: 'URI',
  ): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

  filters: {
    'AdminStatusChanged(address,bool)': TypedContractEvent<
      AdminStatusChangedEvent.InputTuple,
      AdminStatusChangedEvent.OutputTuple,
      AdminStatusChangedEvent.OutputObject
    >;
    AdminStatusChanged: TypedContractEvent<
      AdminStatusChangedEvent.InputTuple,
      AdminStatusChangedEvent.OutputTuple,
      AdminStatusChangedEvent.OutputObject
    >;

    'ApprovalForAll(address,address,bool)': TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    'Lens_Token_AdminStatusChanged(address,bool)': TypedContractEvent<
      Lens_Token_AdminStatusChangedEvent.InputTuple,
      Lens_Token_AdminStatusChangedEvent.OutputTuple,
      Lens_Token_AdminStatusChangedEvent.OutputObject
    >;
    Lens_Token_AdminStatusChanged: TypedContractEvent<
      Lens_Token_AdminStatusChangedEvent.InputTuple,
      Lens_Token_AdminStatusChangedEvent.OutputTuple,
      Lens_Token_AdminStatusChangedEvent.OutputObject
    >;

    'Lens_Token_MaxSupplyUpdated(uint256)': TypedContractEvent<
      Lens_Token_MaxSupplyUpdatedEvent.InputTuple,
      Lens_Token_MaxSupplyUpdatedEvent.OutputTuple,
      Lens_Token_MaxSupplyUpdatedEvent.OutputObject
    >;
    Lens_Token_MaxSupplyUpdated: TypedContractEvent<
      Lens_Token_MaxSupplyUpdatedEvent.InputTuple,
      Lens_Token_MaxSupplyUpdatedEvent.OutputTuple,
      Lens_Token_MaxSupplyUpdatedEvent.OutputObject
    >;

    'Lens_Token_MintRateChanged(uint256)': TypedContractEvent<
      Lens_Token_MintRateChangedEvent.InputTuple,
      Lens_Token_MintRateChangedEvent.OutputTuple,
      Lens_Token_MintRateChangedEvent.OutputObject
    >;
    Lens_Token_MintRateChanged: TypedContractEvent<
      Lens_Token_MintRateChangedEvent.InputTuple,
      Lens_Token_MintRateChangedEvent.OutputTuple,
      Lens_Token_MintRateChangedEvent.OutputObject
    >;

    'Lens_Token_MinterAdded(address,string)': TypedContractEvent<
      Lens_Token_MinterAddedEvent.InputTuple,
      Lens_Token_MinterAddedEvent.OutputTuple,
      Lens_Token_MinterAddedEvent.OutputObject
    >;
    Lens_Token_MinterAdded: TypedContractEvent<
      Lens_Token_MinterAddedEvent.InputTuple,
      Lens_Token_MinterAddedEvent.OutputTuple,
      Lens_Token_MinterAddedEvent.OutputObject
    >;

    'Lens_Token_MinterRemoved(address)': TypedContractEvent<
      Lens_Token_MinterRemovedEvent.InputTuple,
      Lens_Token_MinterRemovedEvent.OutputTuple,
      Lens_Token_MinterRemovedEvent.OutputObject
    >;
    Lens_Token_MinterRemoved: TypedContractEvent<
      Lens_Token_MinterRemovedEvent.InputTuple,
      Lens_Token_MinterRemovedEvent.OutputTuple,
      Lens_Token_MinterRemovedEvent.OutputObject
    >;

    'Lens_Token_OwnershipTransferred(address,address)': TypedContractEvent<
      Lens_Token_OwnershipTransferredEvent.InputTuple,
      Lens_Token_OwnershipTransferredEvent.OutputTuple,
      Lens_Token_OwnershipTransferredEvent.OutputObject
    >;
    Lens_Token_OwnershipTransferred: TypedContractEvent<
      Lens_Token_OwnershipTransferredEvent.InputTuple,
      Lens_Token_OwnershipTransferredEvent.OutputTuple,
      Lens_Token_OwnershipTransferredEvent.OutputObject
    >;

    'Lens_Token_SetMetadataURI(string)': TypedContractEvent<
      Lens_Token_SetMetadataURIEvent.InputTuple,
      Lens_Token_SetMetadataURIEvent.OutputTuple,
      Lens_Token_SetMetadataURIEvent.OutputObject
    >;
    Lens_Token_SetMetadataURI: TypedContractEvent<
      Lens_Token_SetMetadataURIEvent.InputTuple,
      Lens_Token_SetMetadataURIEvent.OutputTuple,
      Lens_Token_SetMetadataURIEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    'URI(string,uint256)': TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
  };
}
