/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicErc20__factory } from "./BasicErc20__factory";
export { Erc20Factory__factory } from "./Erc20Factory__factory";
