/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicErc20__factory } from "./BasicErc20__factory";
export { BasicErc20Factory__factory } from "./BasicErc20Factory__factory";
