name: 'CD: Deploy Canary Release'

on:
  workflow_run:
    workflows: ['CI: Lint, Test, Build']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm for canary release
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Create Canary Release
        id: create_canary
        run: pnpm changeset version --snapshot canary || echo "No unreleased changesets found"

      - name: Check for Changeset
        id: check_changeset
        run: echo "changeset_exists=$(grep -q 'No unreleased changesets found' <<< '${{ steps.create_canary.outputs.stdout }}' && echo false || echo true)" >> $GITHUB_ENV

      # - name: Publish Canary Release
      #   if: env.changeset_exists == 'true'
      #   run: pnpm changeset publish --snapshot --tag canary --no-git-tag
