name: Snapshot Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit
    with:
      include_writes: true

  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Configure NPM Auth Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Create Snapshot
        id: create_snapshot
        run: pnpm changeset version --snapshot canary || echo "No unreleased changesets found"

      - name: Check for Changeset
        id: check_changeset
        run: echo "changeset_exists=$(grep -q 'No unreleased changesets found' <<< '${{ steps.create_snapshot.outputs.stdout }}' && echo false || echo true)" >> $GITHUB_ENV

      - name: Publish Snapshot
        if: env.changeset_exists == 'true'
        run: pnpm changeset publish --snapshot --tag canary --no-git-tag

  examples:
    name: Verify Examples
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Configure NPM Auth Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Lint Examples
        run: |
          pnpm install:examples
          pnpm lint:examples
          pnpm run:examples
