name: 'Verify'
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Lint Code
        run: pnpm lint:code

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Run Tests
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
