name: 'Verify'
on:
  workflow_call:
    inputs:
      include_writes:
        description: 'Run tests for write operations'
        type: boolean
        required: false
        default: false
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Lint Code
        run: pnpm lint:code

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Setup Environment Variables
        shell: bash
        run: echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" > .env

      - name: Run Tests
        run: pnpm test

      - name: Run Write Tests
        if: inputs.include_writes
        run: pnpm test:write

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
